version: 0.0
os: linux
files:
  - source: /
    destination: /appDeploy
file_exists_behavior: OVERWRITE

# NOVO: Garante que os scripts sejam executáveis
permissions:
  - object: /appDeploy/scripts
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 600
      runas: root